#!/bin/sh

if test "$1" != "start"; then
	exit 0
fi

# cache
mkdir -p /var/cache

# dbus
mkdir -p /var/lib/dbus

# usbmount
mkdir -p /var/run

# udev custom rules
mkdir -p /run/udev/

# logs
mkdir -p /var/log

# ensure some holders are available
mkdir -p /var/tmp
mkdir -p /var/opt

# populate the ld cache
mkdir -p /etc
echo -e "/usr/lib\n/lib\n/lib32" | tee /etc/ld.so.conf
ldconfig
