#!/bin/dash
get_key() {
    awk -F= -v k="$1" '$0 !~ /^[[:space:]]*#/ && $1 == k {print $2; exit}' /boot/system-boot.conf 2>/dev/null
}
[ "$(get_key system.usb.gadget)" = "0" ] && { echo "USB gadgets are disabled"; exit 0 ; }

case "$1" in
	start)
        { [ "$(get_key system.usb.gadget.adb)" = "1" ] && /usr/bin/usbgadget adb; } || /usr/bin/usbgadget mtp
    ;;
	stop)
        /usr/bin/usbgadget stop
    ;;
	restart|reload)
		/usr/bin/usbgadget restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}" >&2
		exit 1
		;;
esac
