#!/bin/bash

# only at start AND if triggered
if [ "$1" != "start" ] || [ ! -f /boot/REG_RESCUE ]
then
    exit 0
fi

/usr/bin/plymouth --wait quit --retain-splash

mount -o remount,rw /boot
rm -f /boot/REG_RESCUE

/bin/bash
