#!/bin/sh

# only at start
case "$1" in
start)
	# Unless there is something goin on, let's reboot
	if [ ! -e /tmp/do_not_reboot ]; then
		reboot
	fi
	;;
stop)
	if [ -f /tmp/REG_UPDATE ]; then
		/usr/bin/plymouth change-mode --reboot
	else
		/usr/bin/plymouth change-mode --shutdown
	fi
	/usr/bin/plymouth --show-splash
	;;
*)
	exit 0
	;;
esac
