#!/bin/bash

BOOTCONF="/boot/batocera-boot.conf"

# only at start
test "$1" != "start" && exit 0

# true if triggers are not available or not set to do so
# temp hack
#if ! grep -qE '^[ ]*upgrade[ ]*=[ ]*true[ ]*$' "${BOOTCONF}"
#then
#    exit 0
#fi

# Mount partition
PART=$(batocera-part "share_internal")
mount "${PART}" /userdata

# remove the trigger
# temp hack
# mount -o remount,rw /boot && sed -i -e s+'^[ ]*upgrade'+'#upgrade'+ "${BOOTCONF}" && mount -o remount,ro /boot

# Launch the upgrade
/usr/bin/batocera-upgrade

# reboot
reboot

# Done
exit 0
